version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      # アプリケーションのデフォルト認証情報(https://cloud.google.com/docs/authentication/application-default-credentials?hl=ja)
      - {アプリケーションのデフォルト認証情報のファイルパス}:/root/config/application_default_credentials.js
      - ./re_captcha_scores:/root/output
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/config/application_default_credentials.js
    networks:
      - app-network
  front:
    build: ./front
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
